### ISSUE TITLE
voxelizer.frag中对颜色值的封装是否有问题？

### ISSUE THREAD

**Issue by OnionStark** [AdamYuan/VulkanSVO#1]
文件voxelizer.frag中38行：ucolor & 0x00ffffffu
对比了下你的OpenGL实现，应该是忽略a分量，所以不应该是忽略后8位（ucolor & 0xffffff00u）吗？
我OpenGL和Vulkan不是很熟，目前想参考大佬的这个实现完成一个dx12的版本，希望大佬不吝赐教。

**Comment by AdamYuan** [comment]
packUnorm4x8得到的uint里rgb在后24位，ucolor&0xffu是r，(ucolor&0xff00u)>>8u是g，(ucolor&0xff0000u)>>16u是b，所以是0x00ffffffu没错
（最近忙着高考，没怎么看gh）

**Comment by OnionStark** [comment]
了解了~哈哈，高考加油吖！

**Comment by AdamYuan** [comment]
![Screenshot_2021-01-10_21-48-39](https://user-images.githubusercontent.com/15842404/104124816-c4ab8000-538d-11eb-953c-86ca44fd37db.png)
